"""empty message

Revision ID: 758b2acf83f1
Revises: None
Create Date: 2016-10-17 03:18:18.604283

"""

# revision identifiers, used by Alembic.
revision = '758b2acf83f1'
down_revision = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poker_sessions',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('hand_in_session', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seat_num', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('stack_size', sa.Float(), nullable=True),
    sa.Column('has_button', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_sitting_out', sa.Boolean(), nullable=True),
    sa.Column('is_on_standby', sa.Boolean(), nullable=True),
    sa.Column('poker_session_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['poker_session_id'], ['poker_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poker_hands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street', sa.Integer(), nullable=True),
    sa.Column('bet_sizes', sa.PickleType(), nullable=True),
    sa.Column('hole_cards', sa.PickleType(), nullable=True),
    sa.Column('board', sa.PickleType(), nullable=True),
    sa.Column('poker_session_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['poker_session_id'], ['poker_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poker_hands')
    op.drop_table('players')
    op.drop_table('poker_sessions')
    ### end Alembic commands ###
