"""empty message

Revision ID: 9cb3491e1d3a
Revises: 9f9c2b39e3c6
Create Date: 2016-10-17 03:38:46.658875

"""

# revision identifiers, used by Alembic.
revision = '9cb3491e1d3a'
down_revision = '9f9c2b39e3c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poker_sessions', sa.Column('button_at_seat', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poker_sessions', 'button_at_seat')
    ### end Alembic commands ###
