"""empty message

Revision ID: fa59d64d193c
Revises: 9cb3491e1d3a
Create Date: 2016-10-17 03:49:46.793448

"""

# revision identifiers, used by Alembic.
revision = 'fa59d64d193c'
down_revision = '9cb3491e1d3a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poker_sessions', 'button_at_seat')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poker_sessions', sa.Column('button_at_seat', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
